# Generated by Django 5.2.12 on 2026-03-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='external_quote',
            field=models.TextField(blank=True, null=True),
        ),
    ]
